common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/C4ReplicatorStatus.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/LogTest.java, common/test/java/com/couchbase/lite/ReplicatorOfflineTest.java
This commit removes all of the old platform logic for the OFFLINE state.  It also disables the NetworkReachabilityManager.  CBL-760 tracks re-enabling it
=> CBL-689: Rip out old implementation of OFFLINE

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/ReplicatorChange.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/C4ReplicatorStatus.java, common/test/java/com/couchbase/lite/TestReplicatorChangeListener.java
Abstract Replicator is thread safe
New C4 Database lifecycle support (except: CBL-787)
Document Id feature (still need tests: CBL-792)
This is still pretty big, I am afraid.  (I really am trying to make them smaller!).  Changing the lifecycle of the C4Replicator was a great opportunity finally, to make the Replicator thread-safe.
Note also that several of the complexity warning are gone!  Hurray!
There are still two outstanding problems: CBL-787 (resetCheckpoint doesn't work right) and CBL-792 (need automated tests for DocId)
All existing tests pass.
=> Document Id

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/CMakeLists.txt, common/main/cpp/native_c4listener.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/internal/core/C4Listener.java, common/main/java/com/couchbase/lite/internal/utils/MathUtils.java, common/test/java/com/couchbase/lite/BlobTest.java, common/test/java/com/couchbase/lite/utils/FlakyTest.java
Sketch in C4Listener and its JNI support.
=> Add C4Listener and JNI support

common/main/cpp/native_c4listener.cc
* Fixed bug converting from FLSliceResult to jbyteArray that results to nothing to be copies over.
* Fixed number of name components specified to c4cert_createRequest().
=> Fix generate cert bug in native_c4listener

android/main/java/com/couchbase/lite/internal/replicator/CBLWebSocket.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.java, java/main/java/com/couchbase/lite/internal/replicator/CBLWebSocket.java
* Implemented CBLTrustManager to support listening to server certs received, pinned cert, and accept only self-signed cert feature.
* Updated AbstractCBLWebSocket to use CBLTrustManager.
* Wired up from Replicator -> SocketFactor -> CBLWebSocket -> CBLTrustManager to listen to get server certificates available in the Replicator.
* Reference: CBL-1167 and CBL-1168
=> Implement replicator’s server cert and accept only self-signed cert

common/main/cpp/native_c4listener.cc, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.java
* Updated AbstractCBLWebSocket to use KeyManager for client cert auth.
* Fixed native_c4listiener to setup client certs auth with rootClientCerts pr callback properly.
=> CBL-1169: Implement Client Cert Auth

common/main/cpp/native_c4listener.cc
Add requirePasswordAuth param to startHttp() and startTls() JNI functions to know whether the httpAuthCallback is required to set or not; Setting httpAuthCallback means that the password authentication is enabled.
CBL-1176
=> CBL-1176: Add a param to indicate whether the password auth is required or not

common/main/cpp/native_c4prediction.cc, common/main/cpp/native_fleece.cc, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java
This commit contains two changes:
1) FLSliceResult now implements AutoCloseable.  This is Java's contract that says "you must call close() on this, when you are done with it"
Closing a core-owned object and failing to close a bindings-owned object just generate warnings. They no longer cause exceptions to be thrown.
2) The FLSliceResult heap block allocated in the JNI is now freed.  There are two cases:
a) Java holds ownership of the FLSR: the allocated block is freed when Java frees is companion.
b) Java passes ownership of the FLSR to Core: the allocated block is freed before the FLSR is returned to Core
=> CBL-1440: Fix FLSlice memory leak

common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DatabaseTest.java, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java
Fix for the Java side of the 2.8.0 bug.
I confirm that my tests were passing because the "real" root directory was still .../.couchbase.  The code that fixes the (Android) problem, then, looks for the directory .../.couchbase/.couchbase.  Since it will never find such a directory, I do not believe that the problem has gotten any worse.
Changes are as follows:
- **CouchbaseLiteInternal.java: DEFAULT_ROOT_DIR_NAME is empty:**  This is the main issue.  Changing this effectively fixes the problem.  Everything else is a consequence of changing this.
- **CouchbaseLiteInternal.java: verifyDir:** "".exists() always returns `false`.  Have to get the canonical file before checking for existence.
- **DatabaseTest.java: testReOpenExistingDb:** verify that the default database path no longer ends with …
=> Fix for CBL-1406 Java

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/test/java/com/couchbase/lite/DatabaseTest.java
The new version of c4_setTmpDir should (by my request!) only be called once.
This fix has the platform code calling it only at initialization.
=> Only call setC4TmpDirPath once

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/utils/Preconditions.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.java, common/test/java/com/couchbase/lite/PreInitTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Backport Heartbeat, MaxRetries and MaxRetryWaitTime, now part of 2.8.4
=> Backport Heartbeat, MaxRetries and MaxRetryWaitTime

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java
OkHttp explodes trying to set a ping interval > MAX_INT.  The explosion doesn't happen until the replicator actually tries to connect.
This code uses the same check that OkHttp uses, guaranteeing that if you can set the heartbeat in the config, it will work when the replicator connects.
=> Check heartbeat bounds

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/ArrayInterface.java, common/main/java/com/couchbase/lite/Blob.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/DictionaryInterface.java, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/Fleece.java, common/main/java/com/couchbase/lite/MutableArray.java, common/main/java/com/couchbase/lite/MutableArrayInterface.java, common/main/java/com/couchbase/lite/MutableDictionary.java, common/main/java/com/couchbase/lite/MutableDictionaryInterface.java, common/main/java/com/couchbase/lite/MutableDocument.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/fleece/MArray.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/java/com/couchbase/lite/internal/fleece/MDict.java, common/test/java/com/couchbase/lite/ReplicatorOfflineTest.java
I believe this is the complete JSON API as spec'ed in https://docs.google.com/document/d/1H0mnutn-XXIADvGT_EjINAOVwt0Ea8vwW70v0i_PO54
There is no implementation here.  This is just the API and fixed commenting.
Note that, although not specifically mentioned in the spec, I've updated the interfaces that define the Dictionary and Array APIs
=> CBL-1680: Phase 1, Add JSON API

android/debug/AndroidManifest.xml, android/main/AndroidManifest.xml, android/main/java/com/couchbase/lite/internal/AndroidExecutionService.java, common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java
The Android cert verification process calls, by reflection, a completely non-standard method.
I've added that method and refactored the standard method, so that both use the same code to either defer to the default, or to use the CBL checks.
Also, AsyncTasks have been deprecated in v30.  The Executor that powered them is no longer useful for CBL.  I've replaced it with a small, internal execution service.
Any other changes are just things to get the test code to run
=> v2.8.6: Android API 30 compatibility

common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java
It turns out (you could have knocked me over with a feather) that the thread-pool executor *prefers* enqueuing task to spinning up new threads, as soon as there are CoreThreads threads in the pool.
CBL depends on being able to run at least 4 tasks simultaneously.
=> Increase the size of the CBLExecutor thread pool

common/main/java/com/couchbase/lite/LiveQuery.java, common/main/java/com/couchbase/lite/ResultSet.java, common/test/java/com/couchbase/lite/LiveQueryTest.java
If a live query runs and none of the changes in the database match the query, the query will never updated again.
This is the fix and a test for the fix.  Test fails before the change and succeeds after.
Also necessary re-implementation of a finalizer for ResultSet, in case client code does not properly close it.
Note that this change will be cherry-picked to both the android/release/lithium and the java/release/lithium branches.
=> CBL-2344: A Live Query can stop updating

common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt
This is fixes for:
CBL-2389 | Confirm LiteCore request for close, before connection is opened.
CBL-2395 | Kotlin FullTextIndexConfiguration?.create extension function does not support multiple expressions
=> Lithium fix for CBL-2389 and CBL-2395

common/main/java/com/couchbase/lite/AbstractFunction.java, common/main/java/com/couchbase/lite/Expression.java, common/main/java/com/couchbase/lite/FullTextExpression.java, common/main/java/com/couchbase/lite/FullTextFunction.java, common/test/java/com/couchbase/lite/QueryTest.java
These changes, mandated by the N1QL spec, were totally left out.  They are part of the Lithium release.
Deprecate FullTextExpression and its methods
Add FullTextFunction.match
Re-order args to atan2
Deprecate isNullOrMissing and notNullOrMissing
Add isValued() and isNotValued() expressions
Add tests for all of the above
=> CBL-2416: Comply with new API from N1QL spec

common/main/cpp/native_c4listener.cc
@pasin  found a couple of memory leaks.  This is the fix.
=> Release leaking certs

tools/build_litecore.bat, tools/build_litecore.sh
Add flags to cmake build to prevent it from creating the mbedtls test suite.
=> CBL-2589: stop building mbedtls tests

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
The actual failure documented in the ticket is due to a replicator that doesn't stop.
I *believe* that the replicator doesn't stop because the attempt by
core to close a connection on which the remote already requested a close,
is ignored.  I believe this will fix it.
=> CBL-2593: Replicator delete sometimes fails.

common/main/java/com/couchbase/lite/FileLogger.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/support/Log.java
Apart from fixing the circular dependency, the goal of refactoring C4Log and Log is also to make all getters/setters implementation of C4Log stay within the C4 class level
=> Fix circular dependency and refactor Log

common/main/java/com/couchbase/lite/AbstractDatabase.java
The c4DBChanges array retrieved from LiteCore may contain nulls.  Skip them to prevent NPE.
Backport to 3.0.2
=> CBL-2994: Ignore nulls in c4DbChanges

android/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLTrustManager.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, java/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java
Check all certs provided by the server, for a match with a pinned cert, instead of just the leaf.
Backport to 3.0.2
=> CBL-2974: Check entire server chain for pinned cert

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/SessionAuthenticator.java, common/main/java/com/couchbase/lite/internal/BaseAuthenticator.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java
Correctly handle cookies provide in client supplied custom headers.
Backport to 3.0.2
=> CBL-2417: Session cookies replace header cookies

tools/extract_libs.sh
Java Linux build can't find folder libs in macOS and windows.
=> Fix artifacts downloader

common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Correct handling of SocketTimeoutException.  Similar treatment of PortUnreachableException and NoRouteToHostException
@borrrden : will the use of domain `C4Constants.ErrorDomain.NETWORK` and code `C4Constants.NetworkError.HOST_UNREACHABLE` work in Hydrogen LiteCore?
=> CBL-3023: correctly handle SocketTimeoutException

common/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java
The Android RTE uses an Extended trust manager that does not exist in generic Java.  Back out the code that uses it, for the Java release.
=> CBL-3044: Back Android Extended509TrustManager out of the Java code

tools/extract_libs.sh
Need to exclude both platform names ( "-macos", "-windows") and ".zip" to get the correct artifacts folder.
=> Another attempt at fixing the final packaging

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, tools/extract_libs.sh
For CBSE-11861, make generic SSLExceptions into recoverable errors
=> CBL-3083: Make SSLExceptions recoverable errors

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, tools/extract_libs.sh
CBSE-11861: report generic SSLExceptions to LiteCore as recoverable.
=> CBL-3084: Make SSLExceptions recoverable

common/main/java/com/couchbase/lite/IndexConfiguration.java
According to Pasin, making this type package protected is a violation of the API spec.
It should be visible as an opaque type.
=> CBL-3274: Make IndexConfiguration visible as an opaque type

common/main/java/com/couchbase/lite/FullTextIndex.java, common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java
From the forums: the parameter for FullTextIndex.setLanguage is marked @NonNull.  As described in the documentation immediately above, a null, empty, or unrecognized should disable stemming.
=> CBL-3301: FullTextIndex.setLanguage should accept a null parameter

common/test/java/com/couchbase/lite/BaseCollectionTest.kt, common/test/java/com/couchbase/lite/CollectionListenerTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java
and some refactoring to safely close db.
=> Test Collection API on deleted database

android/main/java/com/couchbase/lite/internal/AndroidConnectivityManager.java
Hotfix for CBSE-12499
When a continuous replication goes offline, it registers an observer to watch for changes in connectivity. The code used to allow a single observer to be registered multiple times. If this happened often enough, the system would throw an uncheck exception: TooManyRequestsException, which will cause the thread to fail.
The heart of the fix is line 313, checking to see if the observer is already in the map.  The try-catch blocks are just bullet-proofing.
=> CBL-3666: Connectivity Manager can be registered multiple times.

android/main/java/com/couchbase/lite/internal/AndroidConnectivityManager.java
These two try-catch blocks were, erroneously, left out of the previous commit.
=> CBL-3666: Catch two more possible exceptions

common/test/java/com/couchbase/lite/BaseDbTest.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/CollectionCrossDbTest.kt, common/test/java/com/couchbase/lite/CollectionListenerTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/MigrationTest.java, common/test/java/com/couchbase/lite/NotificationTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/SaveConflictResolutionTest.kt, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java
These test functions have always confused test. 
There are many tests that assume these functions will complete.  Especially when the a test passes only if a CBL exception, we are in danger of false positives, because one of these methods throws the exception before the test actually executes the code that should cause the error.
=> Separate test functions from cleanup functions

common/main/java/com/couchbase/lite/ListenerToken.java, common/main/java/com/couchbase/lite/QueryChange.java
A couple of small tweaks to production code, suggested by work on tests.
Notably, ListenerToken is now an abstract class
These are all of the changes that affect production code
=> Make ListenerToken abstract

common/test/java/com/couchbase/lite/ConcurrencyTest.java
Windows appears to incorrectly infer that mapToList in ConcurrencyTest.saveDocs throws an Exception, not a RuntimeException.
Wrapping the call in a try-catch block should allow it to compile successfully.
=> Catch mis-inferred exception for Windows

common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseQueryTest.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/BlobTest.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/ConcurrencyTest.java, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/MigrationTest.java, common/test/java/com/couchbase/lite/NotificationTest.java, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/SaveConflictResolutionTest.kt, common/test/java/com/couchbase/lite/utils/KotlinHelpers.java
This commit contains no changes to production code: It is all tests.
=> Remove use of deprecated APIs from most CE tests

common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/main/kotlin/com/couchbase/lite/internal/Helpers.kt, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/kotlin/com/couchbase/lite/CommonConfigFactoryTest.kt
I have reversed my original decision to try to make the Kotlin factories backwards compatible.  Though it worked, as soon as I tried to use it I realized that it was pretty weird and prone to error.
I have deprecated all the original "create" factories and replaced them with new factory methods named "newConfig".  The new versions do not take legacy arguments.
There are a few small changes in the Java code.  The significant changes are in the ConfigurationFactories.  The bulk of the changes are the factory tests.
=> CBL-3863: More straightforward Kotlin factories

common/main/java/com/couchbase/lite/LogFileConfiguration.java, common/test/java/com/couchbase/lite/LogTest.kt
LogFileConfig is already using defaults from the new, autogenerated Defaults file.
Just add tests to verify.
=> CBL-3757: Use Default values in LogFileConfiguration

common/test/java/com/couchbase/lite/QueryTest.java
FTIConfig is already using autogenerated defaults.
Add tests to verify default values and to verify that null (disable language feature) is a legal option.
Note that this does not actually test that setting null actually disables the feature.
=> CBL-3761: Use Default values in FullTextIndexConfiguration

common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt
Again: already using defaults.  Just add a test to be sure they are correct.
Note, again, that the test for a null arg does not actually test null == default resolver
=> CBL-3769: Use Default values in CollectionConfiguration

common/main/java/com/couchbase/lite/Defaults.java, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt
The last of the updates to use defaults.  The only change is splitting the test into two: one test for defaults, the other for backwards compatibility.  Use of the new default is in EE
This uses my approximation of change to the auto-generated Defaults class.  If the real one becomes available, before the push, I will use it instead.
=> CBL-3765:  Use Default values in ReplicatorConfiguration

common/main/java/com/couchbase/lite/internal/fleece/FLValue.java, common/test/java/com/couchbase/lite/internal/ReplicationConfigurationTest.kt, common/test/java/com/couchbase/lite/internal/fleece/FleeceTestHelper.kt
This trivial change makes FLValue.withContent package protected.  It was public so that it could be used from tests.
Changing to this implementation removes a Lint warning and returns the method to package visibility.
=> Package protect FleeceValue.withContent

common/main/java/com/couchbase/lite/internal/core/C4Replicator.java
When I open replicator on a message socket, I was not holding a reference to the Java C4Socket.  It could be GC'ed while the LiteCore companion was still in use.
=> CBL-3952: Hang on to the MessageEndpointListener's C4Socket

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/kotlin/com/couchbase/lite/DeprecatedConfigFactoryTest.kt
An edge case that is a significant bug: Multiple collections may be configured by a single instance of CollectionConfiguration.  The legacy ReplicatorConfiguration mutators mutate the CollectionConfiguration for the default collection.  If the default collection is one of multiple collections configured with a single configuration, then using the legacy mutators will change all of them.
=> CBL-3939: Keep legacy setters from modifying the CollectionConfiguration

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java
I think I have this right now: 0 is the the initial and a legal value both for `set-` and `get-` `maxAttempts`.  It is treated as any other valid value, and translated only when the replicator is started, to an actual legal value depending on the on the setting of `isContinuous`.
=> CBL-3909: get rid of 'maxAttemptSet' kludge

common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/kotlin/com/couchbase/lite/DeprecatedConfigFactoryTest.kt
Remove tests that delete the default collection
=> CBL-3981: Update core; disallow deleting the default collection

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/PlatformTest.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Trivial change makes load tests more relevant.
No changes to production code.
=> CBL-3964: Set per-device timeouts for load tests

common/main/cpp/com_couchbase_lite_internal_core_C4DocEnumerator.h, common/main/cpp/com_couchbase_lite_internal_core_C4Document.h, common/main/cpp/native_c4docenumerator.cc, common/main/cpp/native_c4document.cc, common/main/java/com/couchbase/lite/internal/core/C4DocEnumerator.java, common/test/java/com/couchbase/lite/internal/core/C4DocumentTest.java
There are two that can go.  The rest are used in tests.
=> CBL-4173: Remove unused LiteCore calls

common/main/kotlin/com/couchbase/lite/CommonFlows.kt
Collection.collectionChangeFlow should default its argument, the Executor, to null, making it optional
Ticket: https://issues.couchbase.com/browse/CBL-4283
Targeting the RC2 release
This is very low risk.
=> CBL-4283: Make Collection.collectionChangeFlow's executor argument optional

android-ktx/main/kotlin/com/couchbase/lite/internal/AbstractWorkManagerReplication.kt, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/test/java/com/couchbase/lite/QueryTest.java
=> CBL-4292: The argument to Collection.collectionChangeFlow(Executor?) should be optional

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java
For some reason ReplicatorConfiguration.setAuthenticator disallowed a null argument.
Also fix a minor doc error
=> CBL-4293: ReplicatorConfiguration.setAuthenticator should allow a null argument

common/test/java/com/couchbase/lite/internal/replicator/CBLTrustManagerTest.kt
All of the certs in the CBLTrustManagerTest have expired.  They need to be replaced with valid certs so that the tests can pass
=> Replace expired certs

common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/CouchbaseLiteException.java
The public Javadoc for the Collection class incorrectly describes the constants that name the default class and scope. Getting this doc right is critical
... also, assure that all LiteCore exceptions get logged, even if the CBLExceptions with which they are wrapped, are ignored.
=> Fix Collection documentation; Log LiteCore errors

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/test/java/com/couchbase/lite/LiveQueryTest.java
This commit is a little bigger than it really ought to be:
- In addition to adding a test for the bug fix, I changed several of the other tests to avoid a compiler warning.  Instead of try-finally, they are now try-with-resources.
- There is a publicly visible comment on AbstractQuery.explain that was just really broken
- there were two locks missing in the call to AbstractQuery.addChangeListener: one to protect getC4QueryLocked, and one to protect C4QueryObserver.setEnabled
=> CBL-4423: Stop LiveQueries before closing a DB

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/CollectionChangeNotifier.java, common/main/java/com/couchbase/lite/internal/core/C4ReplicatorStatus.java
This is just so I can get the dev tests to work.  I don't think it is a full fix for the issue.
Also: fix unsafe call to getOpenC4CollectionLocked() and replace C4ReplicatorStatus.copy with a more idiomatic copy constructor.
=> Temporary workaround for CBL-4435: remove stopped replicator from DB active process list

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/ReplicatorOfflineTest.java, common/test/java/com/couchbase/lite/internal/ReplicationConfigurationTest.kt, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollectionTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ReplicatorTest.kt
Dramatic changes... but only to tests.  Nothing in the PR is product code.
=> CBL-3887: Rewrite ReplicationConfigurationTest to avoid deprecated API

common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt
=> CBL-3884: Rewrite PendingDocId test to avoid using deprecated API methods

common/main/java/com/couchbase/lite/AbstractQuery.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java
Also a fix to the LiveQueries class that makes it more sensible.  This is the only change that affects production.
=> CBL-3889: Get URLEndpointListener tests to the new API

common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/QueryTest.java
I think this is the last of the tests still using deprecated API methods (except those that are doing so, on purpose)
When reading these tests I found some of them kind of hard to understand.  I believe that I've also improved that.
=> CBL-3886: Remove deprecated API from MessageEndpointTests

java/main/java/com/couchbase/lite/internal/NativeLibrary.java
This is the first step towards apple silicon support.
The plan (for MacOS) is that there is a single, universal LiteCore lib, but two JNI libs, one for x86_64, the other for aarch64.  This is because I despair of getting gradle to run lipo
```
.
|
macos
/            |             \
aarch64        x86_64         universal
|              |                |
LiteCoreJNI      LiteCoreJNI       LiteCore
```  
There are 3 changes necessary:
- The plugin for Jim's Core puller now puts the litecore binary for MacOS into a directory called "universal"
- The build system processes the whole OS tree ("macos" in this case) into the jar file (not just a single library)
- The NativeLibraries class copies and loads the JNI and LiteCore libraries separately: The former by architecture, the latter from …
=> CBL-4451: Support for Apple Silicon

java/main/java/com/couchbase/lite/internal/NativeLibrary.java
The last change broke Windows: the check for the windows OS that exempted it from the attempt to set permissions on the extracted library was wrong, the lib didn't load, and everything failed.
This change normalizes the check for os type so that it is always done the same way, and explains why it is done this way.
=> Normalize OS identification.

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/replicator/BaseReplicator.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java
An extensive comment describes the choice I mede for implementation.
tl; dr: I believe the intention of the close() method is to do exactly what would happen if the GC got the object, but to do it right now.  That is exactly what this implementation does.  It tells LiteCore to close the replicator and then completely forgets about it.  No zombie objects, no long delays, no unexpected exceptions.
=> CBL-4435:Replicator.close() stops status updates

common/main/kotlin/com/couchbase/lite/CommonFlows.kt
If no explicit `Executor` is provided to listener `Flow`s, use the `Flow`'s `CoroutineDispatcher` as the listener `Executor`.
=> Use Flow's CoroutineContext's dispatcher as listener Executor

android-ktx/main/kotlin/com/couchbase/lite/internal/ReplicatorWorker.kt, common/main/cpp/com_couchbase_lite_internal_fleece_FLEncoder.h, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/internal/core/C4Key.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/internal/fleece/EncodingTest.java
There are some other "in passing" fixes here.  Mostly though, I'd appreciate having you look at `jstringSlice::jstringSlice(JNIEnv *env, jbyteArray jchars)`
That's the heart of the matter.  `testBasicAuthOptions` verifies that the authenticator password option does, in fact, make it to the network code as a string.
=> CBL-1048: char[] encoding in Fleece encoder

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/internal/replicator/InternalReplicatorTest.java
This is a unit test for CBL-4841.
A logic bug caused any document replicated in a pull replication to be scheduled for conflict resolution.
=> Unit test for CBL-4841

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
CBL-4922: Backport: failure in OkHttp authenticator
CBL-4921: Backport: lower the max size on the ClientTask thread pool
CBL-4799: Database.exists should support the default directory
I miss-labeled the branch.  It should be `candidate/3.0.14`, of course.
=> Backport outstanding 3.1 fixes to 3.0

common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/DocumentTest.java
This is just a couple of warnings that come from using Java 17 for the compile
=> Convert 3.1 to use the new build system

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/test/java/com/couchbase/lite/DatabaseTest.java
The test for the incorrect API of Database.exists needs to test for the correct behavior, instead.
=> CBL-4799: Fix test and docs for null param == default dir

common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java
dumb refactor mistake: called nGetBlobStore twice.
=> Fix native crash

common/main/java/com/couchbase/lite/CollectionChangeNotifier.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentChange.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java
This is a group of 4 related changes, each in its own commit:
CBL-4989: Prevent an NPE in the C4Document finalizer.  A user encountered this problem and described it in a forum post.
CBL-4989: A list of null changes should not stop change processing. Root cause of [CBSE-15160](https://issues.couchbase.com/browse/CBSE-15160)
CBL-4991: Null revId is legal in document change. Another bug discovered in the analysis of [CBSE-15160](https://issues.couchbase.com/browse/CBSE-15160)
CBL-4987: Map LiteCore CHANGES domain to platform DATABASE domain. Pasin requested fix.
This is a 3.1.3 release candidate
=> Fix for CBSE-15160

common/main/java/com/couchbase/lite/CollectionChangeNotifier.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentChange.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/listener/ChangeNotifier.java, common/test/java/com/couchbase/lite/LiveQueryTest.java, common/test/java/com/couchbase/lite/NotificationTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ObserverTest.java
A fix for the root cause of CBSE-15160.
Add tests to verify the above fix.
CBL-4992: Null revId is legal in document change
CBL-4988: Map LiteCore CHANGES domain to platform DATABASE domain
=> CBL-4990: A list of null changes should not stop change processing.

common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/ResultSet.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java
Also fix up some logging domain stuff, per .NET
=> CBL-5024: Prevent native crash referencing Result after ResultSet.close()

common/main/java/com/couchbase/lite/AbstractConsoleLogger.java
Small fix for silly oversight.
Will require new 3.1.3 releases for Java, Android and Kotlin
=> CBL-5038: HELIUM: Allow empty log domain list

common/main/java/com/couchbase/lite/AbstractConsoleLogger.java, common/test/java/com/couchbase/lite/LogTest.kt
This is just a silly oversight.
Allow the empty list and add a few tests to confirm that it works
=> CBL-5037: Allow empty log domain list

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Document.h, common/main/cpp/native_c4document.cc, common/main/java/com/couchbase/lite/ConflictResolver.java, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/MutableDocument.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Document.java, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ObserverTest.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Remove C4Document.generation
The default ConflictResolver now depends on a document's timestamp instead of its generation
Fix tests that depended on generation to work with timestamps.
Fix grammar in some comments
=> Support for Version Vectors

common/main/java/com/couchbase/lite/internal/exec/ConcurrentExecutor.java, common/main/java/com/couchbase/lite/internal/exec/ExecutionService.java, common/main/java/com/couchbase/lite/internal/exec/SerialExecutor.java, common/test/java/com/couchbase/lite/BaseTest.java, java/main/java/com/couchbase/lite/ConsoleLogger.java
Client code may wish to be able to decide not to queue additional tasks if too many tasks are already pending
=> CBL-5245: Add 'pending' property to executors

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/ProxyAuthenticator.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/utils/Preconditions.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java
Tests for CBL-5201, CBL-5207, CBL-5213
=> CBL-5213: Proxy auth

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4QueryObserver.h, common/main/cpp/native_c4observer.cc, common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4QueryObserver.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
I removed that Java call to getEnumerator and am now passing results and any error in the callback.
Also added a call to enable(false) in the free method, to guarantee that only the thread-safe version gets called.
=> CBL-5269: Make sure that QueryObs functions are called correctly

android-ktx/main/kotlin/com/couchbase/lite/internal/ReplicatorWorker.kt, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Listener.h, common/main/cpp/native_c4.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/replicator/BaseReplicator.java, common/test/java/com/couchbase/lite/DocumentTest.java
There are several small changes here:
- Fix test bug (found by Jeff Lockhart)
- Improved handling of Replicator.close()
- a new version of C4NativePeer that is void
- test WorkManagerReplicator with the new UniqueWork facility
The big thing, though, is CBL-5280.  There are two conditions under which a JNI LocalRef is released.  The most common one is when a thread returns to the JVM from a call to a native function.  The functions use by LiteCore to call back into Java code *NEVER* do that.  Because they never do it, the LocalRefs are never released.  Apparently, most of callbacks have been made by LiteCore threads which are attached before the callback and then detached after the callback. Fortunately, the second condition under which LocalRefs are released is when a thread is detached. …
=> CBL-5280: Delete LocalRefs

common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/IteratorTest.kt
First steps in the process of normalizing the behavior of collection iterators, across platforms.
In creating this group of tests I've discovered that it makes a difference whether the call to toMutable is on the container or its element.  Will have to add more tests to handle these cases.
testConcurrentModOfSavedArrayIteratorMember fails.  I believe this to be a bug in the Iterator, not the test.
=> Iterator concurrent modification tests

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/Query.java, common/main/java/com/couchbase/lite/internal/core/C4BlobKey.java, common/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionSpec.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentEnded.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/java/com/couchbase/lite/internal/core/C4QueryEnumerator.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/core/peers/PeerBinding.java, common/main/java/com/couchbase/lite/internal/core/peers/TaggedWeakPeerBinding.java, common/main/java/com/couchbase/lite/internal/fleece/FLArrayIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLDictIterator.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/DictionaryTest.java
- C4 classes should be abstract or final
- Get rid of funky @CallSuper annotations
@CallSuper is not well enforced and basically admits that the design is flaky.  It is obviously unnecessary if the class containing the method is final.  Using the template pattern is another way to get rid of it.
=> Clean up some code:

common/main/java/com/couchbase/lite/IndexConfiguration.java, common/main/java/com/couchbase/lite/internal/fleece/FLArray.java, common/main/java/com/couchbase/lite/internal/fleece/FLArrayIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLDictIterator.java, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryTest.java, common/test/java/com/couchbase/lite/internal/replicator/InternalReplicatorTest.java
FL[Dict,Array] iterators no longer return a value.  According to Jens, it is incorrect to use them as a loop control.
Also added comments noting that it is illegal to call next() on an empty iterator, or after it has reached the end of its container.
=> Fix the FL iterators

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Replicator.h, common/main/cpp/native_c4replicator.cc, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/LogFileConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Replicator.java, common/main/java/com/couchbase/lite/internal/replicator/BaseReplicator.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/LogTest.kt, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/ResultTest.java, common/test/java/com/couchbase/lite/mock/ReplicatorMocks.kt
Update to LiteCore 148:
- Add Replicator id to replicator creation methods
- Adjust to changes in Fleece
=> Update to LiteCore 3.2.0-148

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/java/com/couchbase/lite/internal/logging/Log.java, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, java/main/java/com/couchbase/lite/internal/NativeLibrary.java
Log Extension Library extraction: debugging Windows and MacOS library load failure for Java
=> Enable logging during initialization

common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/ResultContext.java, common/main/java/com/couchbase/lite/ResultSet.java
A new context, the ResultContext, assures that ResultSet components hold references to the ResultSet they comprise.
This is is for the Beta 2 release
=> CBL-5597: Add ResultContext to ResultSet

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/java/com/couchbase/lite/internal/logging/Log.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java
Minor but useful changes used in debugging the VS extension library loader.
- Set initial log level to DEBUG when debugging
- Don't crash tests on @Before method failure
=> JAK 3.2.0 beta.2 candidate 2

common/main/java/com/couchbase/lite/CouchbaseLiteError.java, common/main/java/com/couchbase/lite/CouchbaseLiteException.java, common/main/java/com/couchbase/lite/Expression.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java, common/test/java/com/couchbase/lite/LiveQueryTest.java, common/test/java/com/couchbase/lite/QueryChangeTest.java, common/test/java/com/couchbase/lite/QueryTest.java
CBL-5574: Less alarming message on ClientTask executor failure
CBL-5573: Replace the SynchronousQueue on the ClientTaskExecutor
Add Expression.in(List<Expression>)
Add "test" for QueryObserver issue
=> CBL-5572: ClientTask executor should not fail on RejectedExecution

common/main/java/com/couchbase/lite/Expression.java, common/main/java/com/couchbase/lite/internal/core/peers/TaggedWeakPeerBinding.java, common/main/java/com/couchbase/lite/internal/core/peers/WeakPeerBinding.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java
Fix up ClientTask a bit:
- in the unlikely case that we run out of integer tags, throw an exception
- use tags in the range 3 <= tag < Integer.MAX_VALUE - 1.  Those other numbers are just too easy to find, lying around.
- Fix some annotations and some visibility stuff
=> CBL-5672: Prevent unlikely indefinite loop

common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java
Several improvements:
- probably room for as many tasks as the replicator can run at once
- Less hysterical error messages
- *ALL* recoverable errors are now passed to the client  (unfortunately, however, in the case of a replication filter, not all the way to the client)
=> CBL-5653: Improved ClientTask executor

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/DataSource.java, common/main/java/com/couchbase/lite/DatabaseChange.java, common/main/java/com/couchbase/lite/ResultSet.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/test/java/com/couchbase/lite/CollectionQueryTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/MigrationTest.java, common/test/java/com/couchbase/lite/PreInitTest.kt, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/java/com/couchbase/lite/ResultTest.java, common/test/java/com/couchbase/lite/internal/ReplicationConfigurationTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/kotlin/com/couchbase/lite/DeprecatedConfigFactoryTest.kt, common/test/kotlin/com/couchbase/lite/FlowTest.kt, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java
=> CBL-5684: Database.getDefaultCollection() should be non-null

common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/DatabaseChange.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/sockets/OkHttpSocket.java
Also:
CBL-5689: Don't leak basic auth credentials in logs
Important note on dbConfig.get/setDirectory
Fix spelling error in dbChange exception message
=> CBL-5691: Client side proxy does not work

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/main/java/com/couchbase/lite/LiteCoreException.java, common/main/java/com/couchbase/lite/MutableArray.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/ReplicationCollection.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentChange.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/sockets/OkHttpSocket.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/PlatformTest.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Also:
CBL-5689: Don't leak basic auth credentials in logs
- Important note on dbConfig.get/setDirectory
- Fix spelling error in dbChange exception
- Get test initialization right
- Standardize reflection warning
this PR is similar to https://github.com/couchbase/couchbase-lite-java-common/pull/287 but not a cherry-pick
=> CBL-5691: Fix client side proxy auth

common/main/cpp/native_c4.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/FileLogger.java, common/main/java/com/couchbase/lite/MutableArray.java, common/main/java/com/couchbase/lite/internal/ReplicationCollection.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Log.java, common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java, common/main/java/com/couchbase/lite/internal/exec/InstrumentedTask.java, common/main/java/com/couchbase/lite/internal/exec/SerialExecutor.java, common/test/java/com/couchbase/lite/LogTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryObserverTest.kt
This is bigger than it should be.  Sorry about that.  The native crash is the biggest fix.  The ClientTask fix is more contained but, perhaps, more important.  The rest is just preening.
CBL-5729: Prevent native crash on unknown log domain
CBL-5714: API Doc: Can't start a replicator inside a batch block
CBL-5658: Tune the ClientTask executor
CBL-5651: Tests for LiteCore callbacks
=> Several fixes

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryBaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4SocketTest.kt, common/test/java/com/couchbase/lite/utils/TestTimer.java
Although the only ticketable change in this PR, it is not the biggest change.  In addition:
- [Workaround for CBL-5780: Listeners cani't be stopped.](https://github.com/couchbase/couchbase-lite-java-common/commit/28c871aae3e9ba0e4aa4f33aa8b5e13678f8fbae)
- Fix a regression caused by test time-out timer that doubled the time that it took to run a test.
=> CBL-5678: set state to CLOSING in coreRequestClose

common/jni_android.ld, common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/ResultSet.java
Also clean up some ResultSet code
=> Remove getBinaryFileLevel from the public API

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Blob.h, common/main/cpp/com_couchbase_lite_internal_fleece_impl_NativeFLEncoder.h, common/main/cpp/com_couchbase_lite_internal_fleece_impl_NativeFleece.h, common/main/cpp/native_c4blobstore.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4testutils.cc, common/main/cpp/native_fleece.cc, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/Blob.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Blob.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java, common/main/java/com/couchbase/lite/internal/fleece/impl/NativeFLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/impl/NativeFLSliceResult.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4QueryBaseTest.java, common/test/java/com/couchbase/lite/mock/ReplicatorMocks.kt
FLSliceResult now frees the memory block that it frames, in its finalizer. 
This is the change that will be backported to the 3.2 release.
FLSliceResult is also autoclosable, though there are no calls, at at this point, to its close method: it is all up to the finalizer.
Also eliminated an unnecessary instance of FLSliceResult, in Blob handling: the JNI now just returns the blob contents as a Java byte[].
My apologies for the size of the commit.  All test pass.
=> Autoclosable FLSliceResult

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/Blob.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4MutableFleeceTest.java, common/test/java/com/couchbase/lite/internal/core/C4QueryBaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4Test.java, common/test/java/com/couchbase/lite/internal/fleece/EncodingTest.java
All FLSliceResults are now explicitly closed after use.
=> CBL-5795: Explicitly close FLSliceResults

common/main/cpp/native_c4.cc, common/main/cpp/native_c4blobstore.cc, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4database.cc, common/main/cpp/native_c4document.cc, common/main/cpp/native_c4fulltextmatch.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4query.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/cpp/native_c4testutils.cc, common/main/cpp/native_fleece.cc, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4QueryTest.java
This is a pretty big commit.  There are two functional changes:
- Use FLEncoder_GetErrorMessage to give better error messages when the encoder fails
- LocalRefs are explicitly freed as soon as possible (DeleteLocalRef, or DetachCurrentThread)
The rest of the changes (that is, most of them)  are just an attempt to normalize the code:
- logError renamed as jniLog, because it is used to log things other than errors
- pointers are explicitly compared to nullptr for verification
- SliceResults are verified using their bool op
- "auto" used only if the right side of the assignment makes the type absolutely clear.
- FSSliceResults are freed with FLSliceResult_Release; C4Slices are freed with its alias c4slice_free
- boolean returns are now named "ok", pretty much universally.
- some line …
=> CBL-5845: Port LocalRef handling from 3.1

common/main/cpp/com_couchbase_lite_internal_core_C4TestUtils.h, common/main/cpp/native_c4testutils.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Also fix some deprecation annotations
I realize this is likely to change a lot, before 4.0 goes out.  This will, at least, prevent regressions and get the other useful changes
=> Port MMap API to 4_0

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_C4TestUtils.h, common/main/cpp/native_c4testutils.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Index.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Index.java, common/test/java/com/couchbase/lite/ArrayIndexTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
Plumb c4Index_getOptions into the JNI and use it in the ArrayIndex tests
=> CBL-6296: Check unnest path in ArrayIndex tests

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/core/C4BlobKey.java, common/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Blob.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
also: Don't print redundant stack trace on replicator status change
=> CBL-6186: C4Replicator is a C4Peer

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/SessionAuthenticator.java, common/main/java/com/couchbase/lite/internal/BaseAuthenticator.java
Also,  Backport: Don't print redundant stacktrace in replicator status change
These are both just backports of code previously pr'ed  into 4.0
=> Backport CBL-6489: ReplicatorConfiguration.setAuthenticator should not take a ProxyAuthenticator

common/main/cpp/com_couchbase_lite_internal_fleece_impl_NativeFLEncoder.h, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_fleece.cc, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java, common/main/java/com/couchbase/lite/internal/fleece/impl/NativeFLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/impl/NativeFLSliceResult.java
Some renaming, but mostly add an `unbind` method to FLSliceResult and get rid of the Unmanaged and Managed subclasses
=> CBL-6688: Fix FLSliceResult and add unbind method

common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java
Use a dedicated executor for the Custom Logger.  The normal one is instrumented and produces log messages.
=> Don't generate log messages under the callback from LiteCore

common/main/java/com/couchbase/lite/ProxyAuthenticator.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/logging/Log.java, common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java, common/test/java/com/couchbase/lite/logging/LogTest.kt
Also, prevent logging calls during LiteCore log callback
=> CCV-239: Replace Array.equals with MessageDigest.isEqual in proxy authenticator

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_C4TestUtils.h, common/main/cpp/native_c4testutils.cc, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java, common/test/java/com/couchbase/lite/logging/LogTest.kt
Two tests, one for each of the two failure modes.
Instrumentation to support them.
The same instrumentation supports the previously commented out NonASCII test.
... and, fwiw, I found another call to c4log_getDomain and protected it as well.  It is very unlikely that it would ever be called from within the callback.
=> Tests for CBSE-19205

common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java, common/test/java/com/couchbase/lite/internal/ExecutionServiceTest.kt
- Only block the LiteCore callback thread from recursive calls to logging
- Extend the lifetime of the C4Peer cleaner threads from 30 seconds to 5 minutes
- When the logging system fails, add any dropped log message to the failure warning
- Shorten c4Peer/Cleaner thread names so that they make it under the 15-char limit
- Add dumpStats method to c4Peers
=> Several small changes:

common/CMakeLists.txt
I don't know of a way to demonstrate that this works....
... and I'm a bit concerned because Jim's version uses a second "-Wl" in front of the second arg.  My build failed when I tried to do that ( ld: error: unknown argument '-Wl' )
I am assuming that the first -Wl on the line directs the rest of the line to the linker, which does not, of course, understand "-Wl"
=> CBL-6879: Link with 16KB page size

common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/LegacyLogTest.kt
Annotate Document.getTimestamp as @Volatile
Quiet some C4Peer hysterics
Tests that depend on the extension package are skipped if it cannot be loaded…
The actually changes here are very minor.
=> Release candidate 3.2.3 rc 2

common/main/cpp/native_c4replicator.cc, common/main/java/com/couchbase/lite/internal/core/C4Peer.java
Ignore negative (or very large) doc-end bundles and warn on big ones.
=> replace assert with warning

common/main/cpp/native_c4multipeerreplicator.cc
The c4peersync_getPeerInfo method will return null for an unknown peer.  I noticed a crash with the following trace:
```
#00 pc 00000000001d4a5c  /data/app/~~qmcEhVEnDkSR-95aAW4d3w==/com.couchbase.lite.android.mobiletest-54Ma2ww7zK7jRXqZD1D5uQ==/base.apk!libLiteCore.so (offset 0x868000) (BuildId: 9315f8e045c5a84a2c48171af8f0a5f1de7c6334)
#01 pc 00000000001d33ac  /data/app/~~qmcEhVEnDkSR-95aAW4d3w==/com.couchbase.lite.android.mobiletest-54Ma2ww7zK7jRXqZD1D5uQ==/base.apk!libLiteCore.so (offset 0x868000) (c4cert_copyChainData+20) (BuildId: 9315f8e045c5a84a2c48171af8f0a5f1de7c6334)
#02 pc 000000000001b288  /data/app/~~qmcEhVEnDkSR-95aAW4d3w==/com.couchbase.lite.android.mobiletest-54Ma2ww7zK7jRXqZD1D5uQ==/base.apk!libLiteCoreJNI.so (offset 0xc000) …
```
=> Fix null deference in getPeerInfo method

common/main/cpp/native_c4multipeerreplicator.cc
I thought it was only info that was null, but it turns out certificate on a non null info can also be null
=> Fix null pointer deref for real this time

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/CollectionConfiguration.java, common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt
* CBL-7237 : Deprecated ReplicatorConfiguration API for managing collection configurations
* CBL-7239 : Deprecated CollectionConfiguration's constructors without collection and added Set<CollectionConfiguration> getCollectionConfigs().
* In AbstractReplicatorConfiguration's base constructor, extracted from the first collection configurations when the configurations are not null.
* In AbstractReplicatorConfiguration's addCollection() and addCollections() method, asserted that the CollectionConfiguration doesn’t contain the collection object. Basically, the specified CollectionConfiguration object must be created by using the old API.
* In AbstractReplicatorConfiguration, suppress PMD.ExcessivePublicCount, otherwise PMD validation will fail.
* Refactors utility functions in base test class …
=> Made ReplicatorConfiguration consistent with MultipeerReplicatorConfiguration

common/test/java/com/couchbase/lite/logging/LogTest.kt
Updated Kotlinx's delay to thread.sleep as import failure while mobile jenkins build
=> CBL-7354 : Updated Kotlinx's delay to Thread.sleep

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java
* Update ReplicatorConfiguration#getCollections() deprecation message to state it will return Set<CollectionConfiguration> instead of Set<Collection> in the next major release.
* Related to the deprecation message update, add an API note to getCollectionConfigs() indicating it will be renamed to getCollections() in the next major release.
=> CBL-7418 : Update getCollections() Deprecation Message

common/main/cpp/native_c4listener.cc, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
* Fix crash when generating a self-signed certificate without an issuer. In native_c4listener::generateCertificate(), do not release issuerKey if it is the same C4KeyPair passed from Java (owned and managed by the Java side).
* Fix acceptOnlySelfSignedServerCert not working due to incorrect parameter order passed to the CBLTrustManager constructor.
=> CBL-7453 : Fix URLEndpointListenerTest failure

common/main/cpp/native_c4listener.cc, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
-  Fix crash when generating a self-signed certificate without an issuer. In native_c4listener::generateCertificate(), do not release issuerKey if it is the same C4KeyPair passed from Java (owned and managed by the Java side).
- Fix acceptOnlySelfSignedServerCert not working due to incorrect parameter order passed to the CBLTrustManager constructor.
=> CBL-7454 : URLEndpointListenerTests Failed on Java

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, java/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java
* In AbstractCBLWebSocket, swap the order between `acceptAllCerts` and `acceptOnlySelfSignedServerCert`.
* Update the order in Java’s CBLTrustManager to be in sync with the Android version (inline with the order in AbstractCBLTrustManager).
=> CBL-7493 : Fix wrong argument order when creating CBLTrustManager
