couchbase/couchbase-lite-java-common

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/InternalReplicator.java
As part of the work on CBSE 8145, remove this map
=> CBL-805: Remove dangerous CONTEXT_TO_C4_REPLICATOR_MAP

common/test/java/com/couchbase/lite/BaseReplicatorTest.java, java/main/java/com/couchbase/lite/internal/replicator/CBLWebSocket.java
Also: add longer timeout for DB close tests
=> Improved handling of EOFException in Java

common/main/java/com/couchbase/lite/Blob.java, common/test/java/com/couchbase/lite/BlobTest.java
FIx for CBL-2320
Must also be merged to java/release/lithium
=> CBL-2320: BlobOutputStream.read() is returning negative values.

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
This is the hydrogen fix for CBL-2389: Confirm LiteCore request for close, before connection is opened.
=> Hydrogen fix for CBL 2389

common/main/cpp/native_c4listener.cc
Release two certs being leaked in NativeC4Listener.startTls(...)
=> CBL-2540: release leaked certs

common/main/java/com/couchbase/lite/CBLError.java
Errors that are not documented in .NET: 
- NOT_A_DATABASE_FILE 
- HTTP_IM_A_TEAPOT
- WEB_SOCKET_TLS_FAILURE 
- WEB_SOCKET_USER
=> CBL-2551: Include description of error codes

tools/build_litecore.bat, tools/build_litecore.sh
- Get rid of unreference code in build_litecore.sh
- Fix build_litecore.bat
=> Fix build_liteCore files 

common/main/java/com/couchbase/lite/AbstractDatabase.java
=> CBL-2634: Use Priya's 'Uncommitted' message

common/main/java/com/couchbase/lite/internal/core/peers/PeerBinding.java, common/test/java/com/couchbase/lite/internal/core/C4QueryObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/PeerBindingTest.kt
Add a new test suite and move peer binding test from C4QueryObserverTest to that suite
=> ...PeerBinding classes test suite

common/test/java/com/couchbase/lite/LiveQueryTest.java
These tests' main objective is to ensure that the platform behaves in an expected manner, regardless of how long core takes to call back. Thus, I replaced our approximation of query run time (unpredictable) with LONG_TIMEOUT_SEC, and core documented delay.
=> Change delay to make LiveQuery tests more deterministic

common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/sockets/OkHttpSocket.java
Also, get rid of unnecessary wrappings. There will be another PR for the same fix in ee root.
=> Make sure there's no concatenation in logging

common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/support/Log.java
I'm not entirely clear on the goal for this ticket.  Would you please check to be sure I've done the right thing?
=> CBL-2835: enable core logging domains

common/main/java/com/couchbase/lite/internal/replicator/CBLTrustManager.java
Upon approval, will cherry pick this fix into the java release branch, as well
=> CBL-3002: Backport enhanced pinned cert feature

common/main/java/com/couchbase/lite/internal/AbstractSocketFactory.java, common/main/java/com/couchbase/lite/internal/BaseSocketFactory.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/test/java/com/couchbase/lite/internal/core/C4SocketTest.kt
Close the socket and report the error
=> CBL-3055: Better handling of failure creating SocketFromCore

common/main/java/com/couchbase/lite/internal/core/C4Socket.java
Catch any exception thrown during Core attempt to open a remote connection and clean up.
=> CBL-3136: Failure during open may cause a crash

common/test/java/com/couchbase/lite/internal/core/C4CollectionDocObserverTest.kt
-` _default` collection has to be inside `_default` scope
-` testCreateC4CollectionObserver` passes for me, can you check again?
=> Small test fix

common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java
Backport a fix from Helium, that fixes the NPE in C4 object finalization, that some customers are seeing.
=> CBL-3299: eliminate NPE in finalizer

common/test/java/com/couchbase/lite/DbCollectionsTest.kt
Add some edge cases regarding naming scopes and collections, and test CollectionxDatabase
=> The rest of Collection Tests

common/test/java/com/couchbase/lite/DatabaseTest.java, common/test/java/com/couchbase/lite/QueryTest.java
Test for CBL-3135 (core ticket: CBL-3626)
=> Fix query tests according to specs

common/test/java/com/couchbase/lite/AuthenticatorTest.java, common/test/java/com/couchbase/lite/CollectionCrossDbTest.kt, common/test/java/com/couchbase/lite/CollectionListenerTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/ConcurrencyTest.java, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/internal/core/C4AllDocsPerformanceTest.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollatedQueryTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/utils/LoadTest.java, common/test/java/com/couchbase/lite/internal/utils/SlowTest.java, common/test/java/com/couchbase/lite/internal/utils/VerySlowTest.java
Divide tests into 3 groups:
-   .< 2sec runtime: unannotated
-   .> 2sec but < 10 sec runtime: @SlowTest
-   .> 10sec runtime: @VerySlowTest
=> Annotate slow tests

common/main/java/com/couchbase/lite/DocumentChange.java, common/main/java/com/couchbase/lite/Query.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java
Three small tweaks that I discovered I needed to make, while working on tests.
- Make the database name visible to C4Database
- deprecate `Query.removeChangeListener`
- add missing `DocumentChange.getCollection`
=> Fix DocumentChange to return doc collection

common/main/java/com/couchbase/lite/DatabaseChange.java, common/main/java/com/couchbase/lite/ListenerToken.java
Add test-visible method ListenerToken.isActive
Restore deprecated constructor for DatabaseChange
=> A couple of small production changes, before another big Test commit

common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/test/java/com/couchbase/lite/LoadTest.kt
Also, accommodate bizarrely slow Windows Java
=> CBL-3844: Add documentation that clarifies the behavior of AutoPurge

common/main/java/com/couchbase/lite/internal/AbstractSocketFactory.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Socket.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/sockets/CBLSocketException.java, common/main/java/com/couchbase/lite/internal/sockets/OkHttpSocket.java
Extend CBLSocketException to carry an error code and domain
=> Add new error for unknown interface

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/sockets/OkHttpSocket.java, common/test/java/com/couchbase/lite/LoadTest.kt
Also increase the timeouts for the Load tests (again) and some comment refinements
Sorry to include some tweaks in the same commit: It just takes forever to separate them out.  I think they are straightforward.
The significant change is #638 in AbstractCBLWebSocket.
=> CBL-3868: Enable Preemptive Basic Authorization

android/androidTest/java/com/couchbase/lite/internal/AndroidExecutionServiceTest.kt, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/ReplicatorStatus.java, common/test/java/com/couchbase/lite/internal/ExecutionServiceTest.kt
Default Executor thread = UI thread test is only valid on Android
=> Some changes to facilitate the Kotlin WorkManagerReplicator

android-ktx/main/kotlin/com/couchbase/lite/internal/AbstractWorkManagerReplication.kt, android-ktx/main/kotlin/com/couchbase/lite/internal/ReplicatorWorker.kt, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java
Move WorkManager Replication code to common, for use by CBL-Android-CE
=> Work Manager Replication for CE

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Database.h, common/main/cpp/native_c4database.cc, common/main/cpp/native_c4listener.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/Defaults.java, common/main/java/com/couchbase/lite/internal/BaseImmutableReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Database.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/main/java/com/couchbase/lite/internal/replicator/CBLCookieStore.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/test/java/com/couchbase/lite/CookieStoreTest.kt, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ReplicatorTest.kt, common/test/java/com/couchbase/lite/mock/SocketMocks.kt
... also fix a JNI memory leak in Listener.start()
Who knew that such a small thing would require touching 20 different files...
=> CBL-4121: Accept parent domain cookies

common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt
Jim caught some documentation mistakes.
=> Fix config factory documentation

android-ktx/main/kotlin/com/couchbase/lite/internal/ReplicatorWorker.kt, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java
A test of basic functionality for the WorkManager Replication feature.  Testing revealed some issues that are fixed here.
Also: CBL-4294: ReplicatorConfiguration.setAuthenticator should accept null argument
=> CBL-4298: WorkManager Replication tests and fixes

common/main/java/com/couchbase/lite/AbstractReplicator.java
Workaround for hang on db close bug
=> CBL-4484: Closing a replicator hangs closing DB

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
OkHTTP expects a server that wants Auth info, but does not get it, to respond with a challenge.  Under some conditions (anonymous auth) the SGW will simply close the connection, if it does not get the materials.
The solution is to force the Auth header into the first request.
=> CBL-4193: Enable Preemptive Basic Authorization

common/CMakeLists.txt
Update to CMake v3.25
No changes to production code... just production code tools.
=> CBL-4197: Cmake 3.25

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/CouchbaseLiteException.java, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/LiteCoreException.java, common/main/java/com/couchbase/lite/ResultSet.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/LogTest.kt, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/fleece/EncodingTest.java, common/test/java/com/couchbase/lite/mock/TestReplicatorChangeListener.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
also, fix some Report.log calls
=> CBL-4619, CBL-4620: Remove some verbose logging

common/main/java/com/couchbase/lite/CouchbaseLiteException.java, common/main/java/com/couchbase/lite/LiteCoreException.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/LogTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt
A little bit more preening of the log messages....
Also fix the tests that depend on specific message format
=> Fix log dependent tests

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Not a fix.  This will fail the connection, though, not the app
=> CBL-4643: Failure in OkHttp Interceptor

common/main/cpp/native_c4.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/cpp/native_glue.cc, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/ReplicatorStatus.java, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt, common/test/java/com/couchbase/lite/LoadTest.kt
Just some tweaks to make logs clearer.
=> Improved logging

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Before you louse it up, THIMK.
=> CBL-4742: Stop catching IOExceptions in the Ok.Interceptor

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/test/java/com/couchbase/lite/LogTest.kt, etc/pmd/pmd.xml
From Jeff Lockhart
There is a ticket ( CBL-4833 ) to verify the use of the OptIn, before release.
=> Use Flow's CoroutineContext's dispatcher as the default listener Executor

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java
Also: CBL-4837: Make the client task pool size more reasonable
=> CBL-4841: Logic bug in Conflict Resolution

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java
CBL-4836: Make the client task pool size more reasonable
These are both so small that I am combining them.
=> CBL-4842: Logic bug in conflict resolver

common/main/cpp/com_couchbase_lite_internal_fleece_FLEncoder.h, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java
Much improved handling of char[] to Fleece string: Just let std:string copy the java char array
=> CBL-1048: New!  Improved!

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Just clean up some lint that got in during previous fixes
=> Fix static analysis errors

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4DocumentChange.java, common/test/java/com/couchbase/lite/MiscTest.java, common/test/java/com/couchbase/lite/internal/core/C4AllDocsPerformanceTest.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollectionDocObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ObserverTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
Most tests pass with Version Vectors enabled.
Make use of db flags a little more rational
=> Try out Version Vectors

java/main/java/com/couchbase/lite/internal/NativeLibrary.java
Load a universal LiteCore but load a JNI lib for either aarch64 or x86_64.
Tested on my local Mac: all tests pass.  This same code was tested on Apple Silicon, in beryllium.
=> Native lib loader support for Apple silicon

android/androidTest/java/com/couchbase/lite/internal/utils/Report.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DatabaseTest.kt, java/test/java/com/couchbase/lite/internal/utils/Report.java
Get a few minor changes out of the way to make it easier to do the VV stuff.
This includes a couple of doc/signature errors noticed by @jeffdgr8
=> Pre- Version Vector cleanup

common/main/java/com/couchbase/lite/ReplicatedDocument.java
Add spec compliant getters to ReplicatedDocument
=> CBL-5224: Spec compliant getters for ReplicatedDocument

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/ReplicatedDocument.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java
=> CBL-5225: Spec compliant getters for ReplicatedDocument

common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/Scope.java
make getDatabase and getFullName public
=> CBL-5201, CBL-5207: New Collection API

android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/java/com/couchbase/lite/ReplicatedDocument.java, common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/logging/Log.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/ConcurrencyTest.java, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java
The Java platform has been introducing itself as "CBL-ANDROID Initialized...."
=> Small fixes

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/native_c4collection.cc, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/test/java/com/couchbase/lite/LoadTest.kt
Big change at the last minute....
=> Update VS to match new LiteCore API

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/fleece/MArray.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/java/com/couchbase/lite/internal/fleece/MDict.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/CollectionCrossDbTest.kt, common/test/java/com/couchbase/lite/CollectionListenerTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java
Also: 
CBL-5297: Tests fail to delete copied DBs
CBL-5296: Fix error messages
Please note that this is a commit to a release branch and so, must be minimal.
There is an exception, in this commit: normally I would not consider tests as part of "minimal".  In this particular case, there are changes to tests and they are not minimal, because they were expressly requested by a friend of the project.
=> CBL-5309: Fix concurrent modification during iteration

common/main/cpp/native_c4.cc, common/main/cpp/native_c4blobstore.cc, common/main/cpp/native_c4document.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/test/java/com/couchbase/lite/internal/core/C4AllDocsPerformanceTest.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryTest.java
I am going to release this change as a VF for CBSE-16370.
Presuming it all works out, I will merge it into the 3.1.6 release.
It is a big, scary change, so a really careful review is in order.  I am particularly interested in your opinions on the changes I made to jbytearraySlice (in native_glue.[cc,hh])
=> Delete local refs

common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java
A more palatable error message
=> Change log message

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/core/C4QueryEnumerator.java, common/main/java/com/couchbase/lite/internal/fleece/FLArrayIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLDictIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/MValue.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ResultTest.java
Vector, stringToUTC and toJSON tests passing
=> Final cleanup before 3.2.0 release branch

common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/test/java/com/couchbase/lite/LoadTest.kt
CBL-4833: Remove use of OptIn(ExperimentalStdlibApi::class)
This is for Beta.2
=> CBL-5520: Correctly handle exceptions in AbstractReplicator.getOrCreateC4Replicator

common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/test/java/com/couchbase/lite/BaseDbTest.kt
If Aaron was surprised by this, other clients will be baffled.
=> Note in ReplicatorConfiguration.get/setDirectory warns that set != get

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/ArrayInterface.java, common/main/java/com/couchbase/lite/BuilderQuery.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/DictionaryInterface.java, common/main/java/com/couchbase/lite/Query.java, common/main/java/com/couchbase/lite/Result.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/QueryTest.java
Also CBL-5512: setParameters should throw
=> CBL-5512: toJSON should throw

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/ArrayInterface.java, common/main/java/com/couchbase/lite/BuilderQuery.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/DictionaryInterface.java, common/main/java/com/couchbase/lite/Query.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/DictionaryTest.java, common/test/java/com/couchbase/lite/QueryTest.java
CBL-5571: BORON: Query.setParameters should throw
=> CBL-5570: BORON: toJSON should throw

java/main/java/com/couchbase/lite/internal/NativeLibrary.java
Windows VS needs a support library loaded into the same directory as the vs lib.
=> CBL-5604: Load extension support libraries

common/main/cpp/native_flencoder.cc, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/fleece/JSONEncoder.java
=> CBL-5652: toJSON should throw unchecked exception

common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java
Improved ClientTask, ported from HELIUM
=> CBL-5572: Client task should not fail on RejectedExecution exception

common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
=> CBL-5645: Allow socket to close while OPENING

common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/ResultContext.java, common/main/java/com/couchbase/lite/ResultSet.java, common/main/java/com/couchbase/lite/internal/DbContext.java, common/main/java/com/couchbase/lite/internal/fleece/MArray.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/java/com/couchbase/lite/internal/fleece/MContext.java, common/main/java/com/couchbase/lite/internal/fleece/MDict.java, common/test/java/com/couchbase/lite/ResultTest.java
Ported from helium
Note that I've created [CBL-5677](https://issues.couchbase.com/browse/CBL-5677) to investigate improving this stuff
=> CBL-5656: Native crash using ResultSet component after close

common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/ResultContext.java, common/main/java/com/couchbase/lite/ResultSet.java, common/main/java/com/couchbase/lite/internal/DbContext.java, common/main/java/com/couchbase/lite/internal/fleece/MArray.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/java/com/couchbase/lite/internal/fleece/MContext.java, common/main/java/com/couchbase/lite/internal/fleece/MDict.java, common/test/java/com/couchbase/lite/ResultTest.java
=> CBL-5486: Native crash using ResultSet component after close

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/DataSource.java, common/main/java/com/couchbase/lite/DatabaseChange.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/ResultSet.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/test/java/com/couchbase/lite/CollectionQueryTest.kt, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/DbCollectionsTest.kt, common/test/java/com/couchbase/lite/MigrationTest.java, common/test/java/com/couchbase/lite/ReplicatorConfigurationTest.kt, common/test/java/com/couchbase/lite/ResultTest.java, common/test/java/com/couchbase/lite/internal/ReplicationConfigurationTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/kotlin/com/couchbase/lite/DeprecatedConfigFactoryTest.kt, common/test/kotlin/com/couchbase/lite/FlowTest.kt
For compatibility with other platforms.
H/T to @jeffdgr8  for pointing this out and for supplying much of the code.
=> CBL-5683: Database.getDefaultCollection() should be non-null

common/main/java/com/couchbase/lite/AbstractReplicator.java
=> CBL-5712: Doc: Repl cannot be started in batch block

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/ConcurrencyTest.java, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/JSONTest.java, common/test/java/com/couchbase/lite/LiveQueryTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/NotificationTest.java, common/test/java/com/couchbase/lite/PlatformTest.java, common/test/java/com/couchbase/lite/PreInitTest.kt, common/test/java/com/couchbase/lite/QueryChangeTest.java, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorOfflineTest.java, common/test/java/com/couchbase/lite/ResultTest.java, common/test/java/com/couchbase/lite/internal/replicator/BaseReplicatorHack.java, common/test/java/com/couchbase/lite/utils/TestTimer.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Introducing the test timer provided an opportunity for some general test cleanup.
=>  CBL-5742: Clean up test setup/teardown

.gitignore, android/main/java/com/couchbase/lite/ConsoleLogger.java, android/main/java/com/couchbase/lite/CouchbaseLite.java, android/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Log.h, common/main/cpp/native_c4.cc, common/main/java/com/couchbase/lite/AbstractConsoleLogger.java, common/main/java/com/couchbase/lite/FileLogger.java, common/main/java/com/couchbase/lite/Log.java, common/main/java/com/couchbase/lite/LogFileConfiguration.java, common/main/java/com/couchbase/lite/Logger.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Log.java, common/main/java/com/couchbase/lite/internal/logging/Log.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/LogTest.kt, common/test/java/com/couchbase/lite/utils/TestTimer.java, java/main/java/com/couchbase/lite/ConsoleLogger.java, java/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java, java/main/java/com/couchbase/lite/internal/NativeLibrary.java
Some of the things I fixed during the implementation of the new Logging API, can be backported without the new API.
This fixes some test bugs and eliminates some cruft.
=> CBL-5760: Backport some fixes from the Logging branch

common/main/cpp/native_c4query.cc, common/main/cpp/native_glue.cc, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/Parameters.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Document.java, common/main/java/com/couchbase/lite/internal/fleece/FLArray.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/FLValue.java
Just some small fixes that make it easier to work on CBL - 5795
=> Pre CBL - 5795 Cleanup

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Log.h, common/main/cpp/com_couchbase_lite_internal_fleece_FLEncoder.h, common/main/cpp/com_couchbase_lite_internal_fleece_FLSliceResult.h, common/main/cpp/native_c4.cc, common/main/cpp/native_c4database.cc, common/main/cpp/native_fleece.cc, common/main/cpp/native_flencoder.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/Blob.java, common/main/java/com/couchbase/lite/Parameters.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Log.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/FLSliceResult.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryBaseTest.java, common/test/java/com/couchbase/lite/mock/ReplicatorMocks.kt
also: CBL-5848: Dates cannot be encoded as Parameters
=> BL-5846: Backport FLSliceResult memory fix

common/main/cpp/native_c4.cc, common/main/cpp/native_c4blobstore.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4QueryTest.java
A minimal, functionality only, backport of the changes just PRed in Boron
=> CBL-5844: Port LocalRef handling from 3.1

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/native_c4collection.cc, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DocumentTest.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/internal/core/C4SocketTest.kt
Also:
Fix a bug in the return value of Collection.save(MutableDocument, ConflictHandler)
Fix a flaky C4Socket test
=> CBL-5758: LazyVectorIndex and framework

common/CMakeLists.txt, common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Index.h, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4index.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4QueryEnumerator.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/main/java/com/couchbase/lite/internal/fleece/FLArrayIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLDictIterator.java, common/main/java/com/couchbase/lite/internal/utils/Fn.java, common/test/java/com/couchbase/lite/BaseTest.java
At last.  All tests passing.
Maybe not completely caught up with the latest spec.
=> CBL-5752: Lazy Index

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Index.h, common/main/cpp/native_c4index.cc, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/utils/Preconditions.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DictionaryTest.java
Begin update limit should be an int
Use ArrayIndexOutOfBoundsException instead of IndexOutOfBoundsException.  Not an API change since the former is a subclass of the latter.
=> A couple small fixes

common/CMakeLists.txt, common/jni_android.ld, common/main/cpp/NOTE.txt, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Index.h, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4index.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4CollectionObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4QueryEnumerator.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/main/java/com/couchbase/lite/internal/fleece/FLArrayIterator.java, common/main/java/com/couchbase/lite/internal/fleece/FLDictIterator.java, common/main/java/com/couchbase/lite/internal/utils/Fn.java, common/main/java/com/couchbase/lite/internal/utils/Preconditions.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/DictionaryTest.java
This is a simple merge of changes from the 3.2 branch.  There were no significant conflicts.
=> CBL-5752: Lazy Index (#310)

common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java
backport from 3.3
... this is not actually a full on leak, because it would be caught by the finalizer.  Better to close it explicitly ASAP, though
=> CBL-5991: plug memory leak

common/main/cpp/native_c4.cc, common/main/java/com/couchbase/lite/internal/core/C4Document.java, java/main/java/com/couchbase/lite/internal/NativeLibrary.java
pretty much the same as PRs 315 and 316 except delete the local store of domain names
=> CBL-6044: Revert changes from CBL-5729

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Database.h, common/main/cpp/native_c4database.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/Defaults.java, common/main/java/com/couchbase/lite/internal/BaseImmutableDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Database.java, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt
I'm concerned about this, after reviewing Jim's PR.  I concluded that there was no need to consider the full-sync flag in any of the db.copy methods. Perhaps that is not correct?
=> CBL-6068: FullSync option

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_C4TestUtils.h, common/main/cpp/native_c4testutils.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
This really is ever so slightly different than the 3.1 version.
There were enough conflicts so that it is worth reviewing in its entirety.
=> CBL-6072: FullSync option

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_C4TestUtils.h, common/main/cpp/native_c4testutils.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
=> CBL-6121: FullSync option

common/main/cpp/native_c4blobstore.cc
This is identical to https://github.com/couchbase/couchbase-lite-java-common/pull/323
=> CBL-6125: Crash in critical section

common/test/java/com/couchbase/lite/QueryTest.java
Backport of CBL-6413. (https://github.com/couchbase/couchbase-lite-java-common/pull/326)
This change affects only tests and will not be included in 3.1.9
=> CBL-6143: Test for dblock on inBatch

common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/Cleaner.java, common/main/java/com/couchbase/lite/internal/fleece/FLValue.java, common/main/java/com/couchbase/lite/internal/utils/Fn.java, common/main/java/com/couchbase/lite/internal/utils/JSONUtils.java, common/test/java/com/couchbase/lite/internal/core/C4PeerTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java, common/test/java/com/couchbase/lite/internal/fleece/FleeceTestHelper.kt
Also change JSON time converter to UTC
=> CBL-6079: Complete: Implement C4Document on new C4Peer

common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/test/java/com/couchbase/lite/internal/exec/C4PeerTest.kt
Add a couple tests and fix a couple others that were broken.
Some cosmetic changes, as well.
=> CBL-6078: Tests for Cleaner and C4Peer

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/native_c4collection.cc, common/main/java/com/couchbase/lite/ArrayIndexConfiguration.java, common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/java/com/couchbase/lite/IndexConfiguration.java, common/main/java/com/couchbase/lite/ValueIndexConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java
Almost all the way to LiteCore
=> CBL-5176: Implement ArrayIndex API

common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java, common/main/java/com/couchbase/lite/internal/utils/Fn.java, common/test/java/com/couchbase/lite/internal/exec/C4PeerTest.kt, etc/pmd/pmd.xml
=> CBL-6075: Implement phantom ref driven cleaner

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/native_c4collection.cc, common/main/java/com/couchbase/lite/ArrayIndexConfiguration.java, common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/java/com/couchbase/lite/IndexConfiguration.java, common/main/java/com/couchbase/lite/ValueIndexConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/main/java/com/couchbase/lite/internal/exec/CBLExecutor.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/main/java/com/couchbase/lite/internal/exec/ClientTask.java, common/main/java/com/couchbase/lite/internal/utils/Fn.java, common/main/java/com/couchbase/lite/internal/utils/JSONUtils.java, common/test/java/com/couchbase/lite/internal/exec/C4PeerTest.kt, etc/pmd/pmd.xml
Also change Date from string conversion to us UTC instead of GMT.  Mostly irrelevant since times should specify Zulu
=> Backport Cleaner and ArrayIndex

common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/main/java/com/couchbase/lite/internal/fleece/FLValue.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/internal/core/C4CollectionDocObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java, common/test/java/com/couchbase/lite/internal/exec/C4PeerTest.kt, common/test/java/com/couchbase/lite/internal/fleece/FleeceTestHelper.kt
=> C4Database, C4Document and C4Collection use the Cleaner

common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4NativePeer.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/C4Query.java, common/main/java/com/couchbase/lite/internal/core/C4QueryObserver.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/exec/Cleaner.java, common/main/java/com/couchbase/lite/internal/fleece/FLValue.java, common/test/java/com/couchbase/lite/CollectionTest.kt, common/test/java/com/couchbase/lite/internal/core/C4CollectionDocObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java, common/test/java/com/couchbase/lite/internal/exec/C4PeerTest.kt, common/test/java/com/couchbase/lite/internal/fleece/FleeceTestHelper.kt
Backport from master: Convert C4Database, C4Collection , C4Document and  C4Query to the Cleaner
=> CBL-6079: Replace Java finalizer

common/main/cpp/native_c4document.cc, common/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java, common/main/java/com/couchbase/lite/internal/core/C4BlobStore.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Document.java, common/main/java/com/couchbase/lite/internal/core/peers/LockManager.java, common/main/java/com/couchbase/lite/internal/exec/RefQueueCleanerThread.java
Not quite entirely like Jim's but very much inspired by it.
=> CBL-6185: Adopt Jim Borden's Lock Manager

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Database.h, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Document.h, common/main/cpp/native_c4database.cc, common/main/cpp/native_c4document.cc, common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/Collection.java, common/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java, common/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Database.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Document.java, common/main/java/com/couchbase/lite/internal/fleece/FLSharedKeys.java, common/test/java/com/couchbase/lite/CollectionQueryTest.kt, common/test/java/com/couchbase/lite/MigrationTest.java, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
Also better implementations in Blob
=> CBL-6273, CBL-6272: More LockManager in C4Collections, C4Database

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java, common/main/java/com/couchbase/lite/AbstractReplicatorConfiguration.java, common/main/java/com/couchbase/lite/internal/BaseImmutableDatabaseConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/main/kotlin/com/couchbase/lite/CommonFlows.kt, common/test/java/com/couchbase/lite/DatabaseTest.kt, common/test/java/com/couchbase/lite/SimpleDatabaseTest.java, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Also fix some deprecation annotations
=> CBL-6306: MMap API

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Database.h, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4database.cc, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Database.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Database.java, common/test/java/com/couchbase/lite/internal/core/C4BaseTest.java, common/test/java/com/couchbase/lite/internal/core/C4BlobStoreTest.java, common/test/java/com/couchbase/lite/internal/core/C4CollectionObserverTest.kt, common/test/java/com/couchbase/lite/internal/core/C4DatabaseTest.kt, common/test/java/com/couchbase/lite/internal/core/C4ObserverTest.java, common/test/java/com/couchbase/lite/internal/core/C4TestUtils.java
Also CBL-6246: lose the DB_FLAGS constant.
=> CBL-6256: DB flags should be a long

common/jni_android.ld, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Document.h, common/main/cpp/native_c4document.cc, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Document.java, common/test/java/com/couchbase/lite/DocumentTest.java
Straightforward backport from 4.0
=> CBL-6347: backport revHistory

common/main/java/com/couchbase/lite/BasicAuthenticator.java, common/main/java/com/couchbase/lite/SessionAuthenticator.java, common/main/java/com/couchbase/lite/internal/BaseAuthenticator.java
=> CBL-6489: ReplicatorConfiguration.setAuthenticator should not take a ProxyAuthenticator

common/test/java/com/couchbase/lite/CollectionQueryTest.kt
A couple of the tests now pass.
=> CBL-6243 has been fixed

common/main/java/com/couchbase/lite/AbstractReplicator.java
Direct, conflict free port of https://github.com/couchbase/couchbase-lite-java-common/pull/359
=> CBL-6589: Log calls to Replicator.close

common/main/cpp/native_c4listener.cc, common/main/java/com/couchbase/lite/AbstractCollection.java, common/main/java/com/couchbase/lite/Array.java, common/main/java/com/couchbase/lite/ArrayInterface.java, common/main/java/com/couchbase/lite/Blob.java, common/main/java/com/couchbase/lite/CBLConverter.java, common/main/java/com/couchbase/lite/CollectionInterface.java, common/main/java/com/couchbase/lite/Dictionary.java, common/main/java/com/couchbase/lite/DictionaryInterface.java, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/MutableArray.java, common/main/java/com/couchbase/lite/MutableDictionary.java, common/main/java/com/couchbase/lite/ReplicatorStatus.java, common/main/java/com/couchbase/lite/Result.java, common/main/java/com/couchbase/lite/internal/fleece/FLEncoder.java, common/main/java/com/couchbase/lite/internal/fleece/MArray.java, common/main/java/com/couchbase/lite/internal/fleece/MCollection.java, common/main/java/com/couchbase/lite/internal/fleece/MDict.java, common/main/java/com/couchbase/lite/internal/fleece/MRoot.java, common/main/java/com/couchbase/lite/internal/utils/MathUtils.java, common/test/java/com/couchbase/lite/ArrayTest.java, common/test/java/com/couchbase/lite/BaseDbTest.kt, common/test/java/com/couchbase/lite/internal/utils/IOUtils.java, doc/fleece.puml
Several other minor improvements:
- CollectionInterface extended by Array and Dictionary Interfaces
- Remove redundant FLEncodable type
- clean up conversion of Fleece longs to API ints.
- technically correct bool returns in native_c4listener.cc
=> Factor out an AbstractCollections class

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Collection.h, common/main/cpp/native_c4collection.cc, common/main/java/com/couchbase/lite/FullTextIndex.java, common/main/java/com/couchbase/lite/FullTextIndexConfiguration.java, common/main/java/com/couchbase/lite/ValueIndex.java, common/main/java/com/couchbase/lite/ValueIndexConfiguration.java, common/main/java/com/couchbase/lite/internal/core/C4Collection.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Collection.java, common/main/kotlin/com/couchbase/lite/CommonConfigurationFactories.kt, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/PartialIndexTest.kt, common/test/java/com/couchbase/lite/internal/core/C4QueryTest.java, common/test/kotlin/com/couchbase/lite/CommonConfigFactoryTest.kt
Also fix the spelling on the KTX Config Factories
=> Partial Index

common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/logging/LogSinks.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/logging/LogTest.kt
- Better descriptions of the two new tests, now that I understand them.
- Comments on the LogSinks interface: esp the note about asynchronicity.
- Fixed testRecursiveLogging to check only for the reentrant case.
- Up the time limits on some of the Load tests so that they pass more reliably
=> Better logging

common/main/cpp/native_c4.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4prediction.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4socket.cc, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/CouchbaseLiteException.java, common/main/java/com/couchbase/lite/LiteCoreException.java
All tests are passing... but this is C code, so I'd really appreciate a close read.
=> Improved JVM attachement handling

common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Listener.h, common/main/cpp/native_c4listener.cc, common/test/java/com/couchbase/lite/BaseReplicatorTest.kt
Update to LiteCore API 4.0.0-51.  Unfortunately that LiteCore is not ready for prime time, so had to back it out.
=> Prep for new LiteCore

common/CMakeLists.txt, common/main/java/com/couchbase/lite/Collection.java
Port of https://github.com/couchbase/couchbase-lite-java-common/pull/382 to 4.0
=> CBL-6884: Link with 16KB page size.

common/CMakeLists.txt, common/main/java/com/couchbase/lite/Document.java, common/main/java/com/couchbase/lite/internal/core/C4Document.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/logging/LogTest.kt
Quiet some C4Peer hysterics
Now up to date with the 3.2 branch @a3438aefff4b2d2
=> Port 3.2.3rc2 changes to master branch

common/main/java/com/couchbase/lite/AbstractDatabase.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/core/impl/NativeC4Replicator.java, common/main/java/com/couchbase/lite/internal/core/peers/LockManager.java, common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/internal/utils/FlakyTest.java
=> CBL-6904: Convert C4Replicator to new lock strategy

common/test/java/com/couchbase/lite/DatabaseTest.kt
This test would have caught the trivial error that I made in the previous commit
=> Add simple cookies test

common/test/java/com/couchbase/lite/LoadTest.kt, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorMiscTest.java, common/test/java/com/couchbase/lite/internal/utils/FlakyTest.java
=> Update flaky tests

common/CMakeLists.txt, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4Database.h, common/main/cpp/com_couchbase_lite_internal_core_impl_NativeC4MultipeerReplicator.h, common/main/cpp/native_c4.cc, common/main/cpp/native_c4database.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4multipeerreplicator.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4replutils.cc, common/main/cpp/native_c4replutils.hh, common/main/cpp/native_glue.cc, common/main/cpp/native_glue.hh, common/main/java/com/couchbase/lite/internal/ReplicationCollection.java, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/core/C4Replicator.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
It's pretty big.  Sorry about that.
=> Multipeer JNI Code complete

common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java, common/test/java/com/couchbase/lite/ConflictResolutionTest.kt, common/test/java/com/couchbase/lite/QueryTest.java
Also, post presentation: better comments in the C4Peer
=> CBL-7065: Use UTF-8 to encode credentials

android/androidTest/java/com/couchbase/lite/NetworkConnectivityManagerTest.kt, android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/main/cpp/native_c4.cc, common/main/cpp/native_c4collection.cc, common/main/cpp/native_c4database.cc, common/main/cpp/native_c4document.cc, common/main/cpp/native_c4index.cc, common/main/cpp/native_c4listener.cc, common/main/cpp/native_c4multipeerreplicator.cc, common/main/cpp/native_c4observer.cc, common/main/cpp/native_c4replicator.cc, common/main/cpp/native_c4replutils.cc, common/main/cpp/native_c4testutils.cc, common/main/cpp/native_fleece.cc, common/main/cpp/native_flencoder.cc, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/main/java/com/couchbase/lite/internal/core/C4Peer.java, common/test/java/com/couchbase/lite/BaseTest.java, common/test/java/com/couchbase/lite/LegacyLogTest.kt, common/test/java/com/couchbase/lite/PlatformTest.java, common/test/java/com/couchbase/lite/QueryTest.java, common/test/java/com/couchbase/lite/ReplicatorOfflineTest.java, common/test/java/com/couchbase/lite/internal/fleece/EncodingTest.java, common/test/java/com/couchbase/lite/logging/LogTest.kt, java/test/java/com/couchbase/lite/PlatformBaseTest.java
Single idiom for bool > jboolean: (bool) ? JNI_TRUE : JNI_FALSE
Single idiom for jboolean to bool: jboolean != JNI_FALSE
Get rid of redundant skipTestWhen and skipTestUnless
Add LogLevel.NONE to LOG_LEVEL_TO_C4 table
Removed all unverified @Ignore and Assume
There are several remaining, real failures, some of them native crashes.
I wanted to see if any were obviously mine.
=> Review 3_3 dev tests

common/main/cpp/native_c4listener.cc
1. The DEFER cannot be inside the if because, duh, it will immediately free the material I just made
2. key was getting freed twice from a typo where I meant to use "value"
=> Fix some native crashes in the generateCACert path

common/main/java/com/couchbase/lite/AbstractQuery.java, common/main/java/com/couchbase/lite/AbstractReplicator.java, common/main/java/com/couchbase/lite/Query.java
Removed the APIs for Query, Replicator
=> CBL-7295 : Remove Deprecated Change Listener APIs

android/androidTest/java/com/couchbase/lite/PlatformBaseTest.java, common/main/cpp/native_c4.cc, common/main/java/com/couchbase/lite/internal/core/C4Constants.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java, common/test/java/com/couchbase/lite/QueryTest.java
=> Add new mDNS logging domain

common/main/java/com/couchbase/lite/LogDomain.java, common/main/java/com/couchbase/lite/internal/core/C4Log.java
=> CBL-7395: Add mDNS log domain
